spring:
  datasource:
    url: jdbc:mysql:///ojdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  userparam:
      absoluteDir: /Users/wangwei/ojtest
server:
  port: 8181