spring:
  datasource:
    url: jdbc:mysql://106.55.166.98:3306/ojdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ojdb
    password: arihLMkbxNpt3XBH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  userparam:
      absoluteDir: /Users/wangwei/ojtest
server:
  port: 8181